export const courses = [
  {
    uid: 1,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-1.jpg",
    userImage: "/images/avatar/avatar-1.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 2,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-2.jpg",
    userImage: "/images/avatar/avatar-2.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 3,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-3.jpg",
    userImage: "/images/avatar/avatar-3.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 4,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-4.jpg",
    userImage: "/images/avatar/avatar-4.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 5,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-5.jpg",
    userImage: "/images/avatar/avatar-5.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 6,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-6.jpg",
    userImage: "/images/avatar/avatar-6.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 7,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-3.jpg",
    userImage: "/images/avatar/avatar-3.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 8,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-4.jpg",
    userImage: "/images/avatar/avatar-4.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
  {
    uid: 9,
    title: "Fashion Photography From Professional",
    tag: "Photography",
    image: "/images/products/product-5.jpg",
    userImage: "/images/avatar/avatar-5.jpg",
    rating: 4,
    lessons: 12,
    duration: "8min",
    price: 415.99,
    discount: 959,
  },
];

export const footerSections = [
  {
    title: "Learn English With Us",
    links: [
      {
        label: "British Accent Training – Start Speaking Confidently",
        url: "/courses/british-accent-training",
      },
      {
        label: "Essential Grammar for Beginners",
        url: "/courses/grammar-beginners",
      },
      {
        label: "Real-Life English Conversations",
        url: "/courses/real-life-conversations",
      },
      {
        label: "Listening & Comprehension Practice",
        url: "/courses/listening-practice",
      },
      {
        label: "Common British Idioms Explained",
        url: "/courses/british-idioms",
      },
      {
        label: "British English for IELTS & Cambridge Exams",
        url: "/courses/exam-prep",
      },
    ],
  },
  {
    title: "Stay Connected",
    links: [
      { label: "Facebook", url: "https://facebook.com/LearnBritishNow" },
      {
        label: "YouTube – British English 101",
        url: "https://youtube.com/BritishEnglish101",
      },
      {
        label: "Instagram – @british.english.learn",
        url: "https://instagram.com/british.english.learn",
      },
      { label: "Email Us", url: "mailto:hello@britishenglishlearn.com" },
      { label: "Newsletter Signup", url: "/newsletter" },
      { label: "Listen to Our Podcast", url: "/podcast" },
    ],
  },
  {
    title: "Useful Resources",
    links: [
      { label: "About Our Mission", url: "/about" },
      { label: "Student Testimonials", url: "/testimonials" },
      { label: "Learning Roadmap", url: "/roadmap" },
      { label: "Download Mobile App", url: "/app" },
      { label: "Support Center", url: "/support" },
      { label: "FAQs", url: "/faq" },
    ],
  },
  {
    title: "Join Our Community",
    links: [
      { label: "English Speaking Club", url: "/community/speaking-club" },
      { label: "Student Forum", url: "/community/forum" },
      { label: "Events & Webinars", url: "/events" },
      { label: "Success Stories", url: "/success-stories" },
      { label: "Become a Tutor", url: "/join-as-tutor" },
      { label: "Affiliate Program", url: "/affiliate" },
    ],
  },
];
